Repository wecode-bootcamp-korea/27-2nd-Hines-backend, pull requests merged in 2021-12, with the labels that each got.

#3 Modify: product 모델 description 추가
  .gitignore
  cart/migrations/0001_initial.py
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/models.py
  users/migrations/0001_initial.py
Labels: Status: Rebase 요청

#5 Modify: CorsMiddleware추가
  .gitignore
  teamhines/settings.py
Labels: Status: 리뷰 요청

#2 Add: 프로덕트 리스트 기능구현
  products/tests.py
  products/urls.py
  products/views.py
  teamhines/settings.py
  teamhines/urls.py
Labels: Status: 리뷰 요청

#4 Add: product 상세 기능 구현
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#6 Add: KakaoLoginView 구현, test code 첨부
  20211216_teamhines.sql
  requirements.txt
  teamhines/settings.py
  teamhines/urls.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#9 Add: decorator 구현
  core/decorator.py
Labels: Status: 리뷰 요청

#7 Add: 프로덕트 리스트 by category 기능추가, 유닛테스트 추가
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#8 Add : review 기능구현
  .gitignore
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#10 Add: orders_view 구현, decorator 적용, UnitTests 추가
  Dockerfile
  cart/views.py
  orders/tests.py
  orders/urls.py
  orders/views.py
  teamhines/settings.py
  teamhines/urls.py
Labels: Status: 리뷰 요청

#11 Modify: 프로덕트 리스트 by category_id 기능추가
  products/tests.py
  products/views.py
Labels: Status: 리뷰 요청

#13 Modify: 리뷰반영, 프로덕트 리스트뷰, 카테고리뷰 수정
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#14 Add: 장바구니 기능 구현, 유닛테스트
  cart/tests.py
  cart/urls.py
  cart/views.py
  products/models.py
  teamhines/urls.py
Labels: Status: 리뷰 요청

#15 Modify: 리뷰 반영, 가져오는 사용자 정보 추가
  users/views.py
Labels: Status: 리뷰 요청

#16 Modified : 리뷰 반영, ReviewView unit test 작성
  20211216_teamhines.sql
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#17 Modify: CartView에 product_image 추가
  cart/views.py
Labels: Status: 리뷰 요청

#18 Modify: CartView수정, patch 에러추가, urls.py 수정
  cart/urls.py
  cart/views.py
Labels: Status: 리뷰 요청

#19 Modified:리뷰 정보 불러오기 API
  products/views.py
Labels: Status: 리뷰 요청

#20 Modify: CartView수정
  cart/views.py
  orders/views.py
Labels: Status: Accepted

#21 Modify: users/views.py 수정
  cart/tests.py
  users/tests.py
Labels: Status: 리뷰 요청
